###

GET http://localhost:3000/post

###
GET http://localhost:3000/post/6939843cb1b375d9dca8e477

###
POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "New Post Title",
  "content": "This is the content of the new post.",
  "sender": 333333333
}

###
GET http://localhost:3000/post?sender=333333333